// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwRYg3nEuYSIv0vbyykErJMffjzs5SBY',
    appId: '1:920244756124:web:a2d5bf35f7cd0ee8efd759',
    messagingSenderId: '920244756124',
    projectId: 'mlptechster-a33e2',
    authDomain: 'mlptechster-a33e2.firebaseapp.com',
    storageBucket: 'mlptechster-a33e2.appspot.com',
    measurementId: 'G-X7Y9VYSWX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWYcO29KPTT06oK08tVFlqtyT6ejnOLzc',
    appId: '1:920244756124:android:9577c88734522042efd759',
    messagingSenderId: '920244756124',
    projectId: 'mlptechster-a33e2',
    storageBucket: 'mlptechster-a33e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClumMNp35ZmPVHk0efhuzHhlK4f0UqeN4',
    appId: '1:920244756124:ios:bac4dabe0807e3f7efd759',
    messagingSenderId: '920244756124',
    projectId: 'mlptechster-a33e2',
    storageBucket: 'mlptechster-a33e2.appspot.com',
    iosBundleId: 'com.example.mlpAdministration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClumMNp35ZmPVHk0efhuzHhlK4f0UqeN4',
    appId: '1:920244756124:ios:bac4dabe0807e3f7efd759',
    messagingSenderId: '920244756124',
    projectId: 'mlptechster-a33e2',
    storageBucket: 'mlptechster-a33e2.appspot.com',
    iosBundleId: 'com.example.mlpAdministration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgwRYg3nEuYSIv0vbyykErJMffjzs5SBY',
    appId: '1:920244756124:web:685d06967d20401cefd759',
    messagingSenderId: '920244756124',
    projectId: 'mlptechster-a33e2',
    authDomain: 'mlptechster-a33e2.firebaseapp.com',
    storageBucket: 'mlptechster-a33e2.appspot.com',
    measurementId: 'G-PQDS0ZCGXE',
  );
}
